version: '2.1'
services:

  always500:
    image: httpd:2.4-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
      - "./.htaccess:/usr/local/apache2/htdocs/.htaccess:ro"
